#!/usr/bin/env bash
# Configure a nginx with response header
apt-get update
apt-get install nginx -y
ufw allow 'Nginx HTTP'
echo "Hello World!" | tee /var/www/html/index.nginx-debian.html
new_string="listen 80 default_server;\\nerror_page 404 \/404.html;\\n\\tlocation = \/404.html {\\n\\t\\troot \/usr\/share\/nginx\/html;\\n\\t\\tinternal;\\n\\t}"
sed -i "s/listen 80 default_server;/$new_string/" /etc/nginx/sites-enabled/default
new_string2="http {\\n\\tadd_header X-Served-By \"$HOSTNAME\";"
sed -i "s/http {/$new_string2/" /etc/nginx/nginx.conf
service nginx restart
